### ISSUE TITLE
Strange behaviour !!

### ISSUE THREAD

**Issue by khelifk** [JennyDigital/OriClone-1#3]
Hi Jenny,
For the past few days, I've encountered an unusual problem with OriClone. Upon powering it up, the keyboard becomes unresponsive, and a continuous "*" character appears on the screen persistently, even after disconnecting the keyboard, tried to change the Rams, the Multiplexers, Roms, Pia, removed the sound procesor, but same behavior.
the keyboard I am using is working fine, do you have any idea what can cause such issue ?
thank you,
Kamel

**Comment by khelifk** [comment]
![IMG_20240415_220523](https://github.com/JennyDigital/OriClone-1/assets/81188223/5df8331a-f2a7-4fde-8562-df9683b1675a)

**Comment by JennyDigital** [comment]
Check around the AY IOA0, VIA PB0-3, check transistor 2, between pins 12, 13 and 14 on the keyboard connector (motherboard side).  If your AY and VIA are socketed a could swap them out to see what happens too.

There are _many_ iffy AY's out there.

The basic principle of how the keyboard on the Oric line of computers works is as follows.  The VIA drives the row selection through pins PB0-2, and the columns through the AY's port A.  When a key is pressed it returns this signal through the KB_INT line that pulls PB3 low using transistor 2.

I note that * is on row 7, column 0, and right shift is also on row 7, but column 4.  Left shift is on  row 4, column 4.  I would imagine the keyboard scanning routines would start at one corner of the matrix and work through systematically though I haven't seen that bit of code.

**Comment by khelifk** [comment]
Hello Jenny, you saw correctly, the issue was located at transistor 2, the problem was a poor contact at the base of this transistor. I think the PCB I made is of poor quality (bad contacts), I will redo it in China, but before that I plan to make some modifications for the Din 7 and 8 connectors because I can't find them locally, I will go for the same connectors but with a different pins configuration, so I need to remake the Pcb manually to match the available connectors.
Anyway, I'm having as much fun as a kid, between testing and BASIC programming... thank you very much for that !!

**Comment by JennyDigital** [comment]
Not a problem!  I enjoy helping people.  BTW, I see that you are also ride a BMW.  Mine's an R1150R.  Take care!

**Comment by khelifk** [comment]
Oh...It's cool that we share a love for BMW bikes.  Perhaps one day we'll have the opportunity to go for a ride together on our BMWs...who knows...until then ride safe and take care !
